#!/usr/bin/env bash
#
# Installs all cargo-managed dependencies required to build Warp release
# artifacts (e.g., bundled license generation).

# This script should be platform-agnostic (eg. no unix-only references like /dev/null).

NO_BUILD_DEPS=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --no-build-deps)
      NO_BUILD_DEPS=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

if [ "$NO_BUILD_DEPS" = false ]; then
  "$PWD"/script/install_cargo_build_deps
fi

# Install cargo-about for generating third-party license attribution.
if command -v cargo-binstall >/dev/null 2>&1; then
  cargo binstall --force -y cargo-about@0.8.4 || cargo install --locked cargo-about@0.8.4
else
  cargo install --locked cargo-about@0.8.4
fi
